// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecent(arg1) {
  return window['go']['main']['App']['AddRecent'](arg1);
}

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ClearRecents() {
  return window['go']['main']['App']['ClearRecents']();
}

export function ClipboardGet() {
  return window['go']['main']['App']['ClipboardGet']();
}

export function ClipboardSet(arg1) {
  return window['go']['main']['App']['ClipboardSet'](arg1);
}

export function ExportPDF(arg1, arg2) {
  return window['go']['main']['App']['ExportPDF'](arg1, arg2);
}

export function ListDir(arg1) {
  return window['go']['main']['App']['ListDir'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RefreshMenu() {
  return window['go']['main']['App']['RefreshMenu']();
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2, arg3);
}

export function SetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['SetAlwaysOnTop'](arg1);
}

export function SetDirty(arg1) {
  return window['go']['main']['App']['SetDirty'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function SetScrollSync(arg1) {
  return window['go']['main']['App']['SetScrollSync'](arg1);
}

export function SetTypewriter(arg1) {
  return window['go']['main']['App']['SetTypewriter'](arg1);
}

export function SnapshotDocKey(arg1) {
  return window['go']['main']['App']['SnapshotDocKey'](arg1);
}

export function SnapshotList(arg1) {
  return window['go']['main']['App']['SnapshotList'](arg1);
}

export function SnapshotRead(arg1, arg2) {
  return window['go']['main']['App']['SnapshotRead'](arg1, arg2);
}

export function SnapshotWrite(arg1, arg2) {
  return window['go']['main']['App']['SnapshotWrite'](arg1, arg2);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function WatchDir(arg1) {
  return window['go']['main']['App']['WatchDir'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
