// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportPDF(arg1:string,arg2:string):Promise<string>;

export function ListDir(arg1:string):Promise<Array<main.DirEntry>>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SaveImage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SetDirty(arg1:boolean):Promise<void>;

export function SnapshotDocKey(arg1:string):Promise<string>;

export function SnapshotList(arg1:string):Promise<Array<main.SnapshotMeta>>;

export function SnapshotRead(arg1:string,arg2:string):Promise<string>;

export function SnapshotWrite(arg1:string,arg2:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
