// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ListDir(arg1:string):Promise<Array<main.DirEntry>>;

export function OpenDirectoryDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
